### ISSUE TITLE
There should be one file per merge statement

### ISSUE THREAD

**Issue by zippy1981** [GoEddie/MergeUi#3]
How I would do it (what would make this work seamlessly with my current workflow).
- Create new files in the same place as the current post deploy script
- Call it schema.table.data.sql
- :r the script into the post deploy script.

**Comment by GoEddie** [comment]
yo, in this version the best you could do is generate it in the post deploy script then move it where you want.

the next version (I am working on at the moment) will be script based rather than table based so instead of choosing, project, schema, table you choose which of the script files there are in the project and add whatever tables you want. 

this means two things, first you can have a table in a file referenced by the :r import and secondly you can have the same table multiple times if you want different data in different environments etc.

should be done in a week or so

**Comment by GoEddie** [comment]
I have finished the next version (moved to another repo) that lets you do this, instead of finding a post deploy script and using that this lets you put the merge in any script file:

https://github.com/GoEddie/SSDT-DevPack/blob/master/release/SSDTDevPack.VSPackage.1.0.vsix?raw=true
